services:
  backend:
    container_name: cat_vpn_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    command: python -m backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  frontend:
    container_name: cat_vpn_frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: http-server dist
    restart: on-failure
    depends_on:
      - backend

  postgres:
    container_name: cat_vpn_db
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "./db_data:/var/lib/postgresql/data"

  redis:
    container_name: cat_vpn_redis
    image: redis:latest
    restart: unless-stopped
    command:
      - redis-server

  nginx:
    container_name: cat_vpn_nginx
    build: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  db_data: