"""add unique constraint to tid in keys

Revision ID: 29735d34ef57
Revises: d16269a02269
Create Date: 2025-08-29 20:02:29.928014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29735d34ef57'
down_revision: Union[str, Sequence[str], None] = 'd16269a02269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'keys', ['tid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keys', type_='unique')
    # ### end Alembic commands ###
