"""
Initial migration

Revision ID: d16269a02269
Revises: 
Create Date: 2025-08-15 11:59:53.554720

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d16269a02269"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("tid", sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column("first_name", sa.String(), nullable=False),
    sa.Column("last_name", sa.String(), nullable=True),
    sa.Column("username", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("tid")
    )
    op.create_table("keys",
    sa.Column("vpn_key_id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("unique_key", sa.String(), nullable=False),
    sa.Column("valid_until", sa.DateTime(), nullable=True),
    sa.Column("tid", sa.BigInteger(), nullable=False),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["tid"], ["users.tid"], onupdate="CASCADE", ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("vpn_key_id"),
    sa.UniqueConstraint("unique_key")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("keys")
    op.drop_table("users")
    # ### end Alembic commands ###
